name: .NET

on:
  push:
    branches: [ main ]
    paths: ./Library/**

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
        source-url: https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json
      env:
        NUGET_AUTH_TOKEN: '%NUGET_AUTH_TOKEN%'
    - name: Restore dependencies
      run: dotnet restore ./Library
    - name: Build
      run: dotnet build ./Library/MyDemoSharedLibrary.sln --configuration Release --no-restore
    - name: Pack
      run: dotnet pack ./Library/MyDemoSharedLibrary.sln --no-build --configuration Release
    - name: Publish
      run: dotnet nuget push ./Library/bin/Release/*.nupkg --skip-duplicate
      env:
        NUGET_AUTH_TOKEN: ${{ github.token }}
